<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Apprenant extends \App\Entity\Apprenant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Tel', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'DateNaissance', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Ville', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Git', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Avatar', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'reseaux', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'offres', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'promoAppres'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Tel', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'DateNaissance', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Ville', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Git', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'Avatar', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'reseaux', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'offres', '' . "\0" . 'App\\Entity\\Apprenant' . "\0" . 'promoAppres'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Apprenant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFullname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullname', []);

        return parent::getFullname();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $Nom): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$Nom]);

        return parent::setNom($Nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $Prenom): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$Prenom]);

        return parent::setPrenom($Prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(string $Tel): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$Tel]);

        return parent::setTel($Tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $DateNaissance): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$DateNaissance]);

        return parent::setDateNaissance($DateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $Adresse): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$Adresse]);

        return parent::setAdresse($Adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $Ville): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$Ville]);

        return parent::setVille($Ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getGit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGit', []);

        return parent::getGit();
    }

    /**
     * {@inheritDoc}
     */
    public function setGit(?string $Git): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGit', [$Git]);

        return parent::setGit($Git);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar(?string $Avatar): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', [$Avatar]);

        return parent::setAvatar($Avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getReseaux(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReseaux', []);

        return parent::getReseaux();
    }

    /**
     * {@inheritDoc}
     */
    public function addReseaux(\App\Entity\Reseau $reseaux): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReseaux', [$reseaux]);

        return parent::addReseaux($reseaux);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReseaux(\App\Entity\Reseau $reseaux): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReseaux', [$reseaux]);

        return parent::removeReseaux($reseaux);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffres(): ?\App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffres', []);

        return parent::getOffres();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffres(?\App\Entity\Offres $offres): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffres', [$offres]);

        return parent::setOffres($offres);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoAppres(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoAppres', []);

        return parent::getPromoAppres();
    }

    /**
     * {@inheritDoc}
     */
    public function addPromoAppre(\App\Entity\PromoAppre $promoAppre): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPromoAppre', [$promoAppre]);

        return parent::addPromoAppre($promoAppre);
    }

    /**
     * {@inheritDoc}
     */
    public function removePromoAppre(\App\Entity\PromoAppre $promoAppre): \App\Entity\Apprenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromoAppre', [$promoAppre]);

        return parent::removePromoAppre($promoAppre);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

}
