<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2KVg21\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2KVg21/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2KVg21.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2KVg21\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2KVg21\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2KVg21',
    'container.build_id' => 'f0695ec2',
    'container.build_time' => 1592827381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2KVg21');
